### ISSUE TITLE
Tooltip is not a function

### ISSUE THREAD

**Issue by nomadicjosh** [toolstack/Glot-O-Matic-Core#10]
I am new user of GlotPress/Glot-O-Matic. The only issue I've come across is a javascript issue which also causes an issue with "Use as name" link when Creating a New Translation Set. By commenting out that section, it fixes the issue I am having. I know that the code is found in GlotPress as well, but maybe it has to do with when it loads? Please see screenshot.

![tooltip](https://cloud.githubusercontent.com/assets/2042176/10708824/f3daab82-79e3-11e5-8641-64b5bc87fde8.png)

**Comment by toolstack** [comment]
Can you provide the steps required to reproduce the issue?

**Comment by nomadicjosh** [comment]
With regards to the tooltip issue itself, it is present once you visit an installation. No matter what page you navigate to, the error is present. I was using safari and used the inspect element under developer tools to see the actual error in the above screenshot.

With regards to my specific issue, please see steps below:
1. Log in
2. Click on project
3. Click on project actions
4. Click on new translation set
5. Choose locale from drop down
6. When you click use as name, it should populate the next input field, but nothing happens.

**Comment by toolstack** [comment]
It's a bug in the original GlotPress code, it doesn't load the jquery-ui code for the new translation set page.

I'll commit a fix for the next release.

**Comment by toolstack** [comment]
Fix included in https://github.com/toolstack/Glot-O-Matic-Core/commit/d622e3f677f4e53473e0a0379b292f6021c9dc55.
